[project]
description = "urfu-programming"
name = "urfu-programming"
readme = "README.md"
version = "0.1.0"

dependencies = [  ]
requires-python = ">=3.13,<3.14"

[dependency-groups]
dev = [ "ruff", "ty" ]
